# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(1000, 700))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 300))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setMinimumSize(QtCore.QSize(400, 300))
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_monitor = QtWidgets.QWidget(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_monitor.sizePolicy().hasHeightForWidth())
        self.widget_monitor.setSizePolicy(sizePolicy)
        self.widget_monitor.setObjectName("widget_monitor")
        self.horizontalLayout_3.addWidget(self.widget_monitor)
        self.horizontalLayout_2.addWidget(self.groupBox_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(450, 350))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_autorun_start = QtWidgets.QPushButton(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_autorun_start.sizePolicy().hasHeightForWidth())
        self.pushButton_autorun_start.setSizePolicy(sizePolicy)
        self.pushButton_autorun_start.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_start.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_start.setObjectName("pushButton_autorun_start")
        self.gridLayout_4.addWidget(self.pushButton_autorun_start, 0, 0, 1, 1)
        self.pushButton_autorun_stop = QtWidgets.QPushButton(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_autorun_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_autorun_stop.setSizePolicy(sizePolicy)
        self.pushButton_autorun_stop.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_stop.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_stop.setObjectName("pushButton_autorun_stop")
        self.gridLayout_4.addWidget(self.pushButton_autorun_stop, 0, 1, 1, 1)
        self.pushButton_autorun_charge = QtWidgets.QPushButton(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_autorun_charge.sizePolicy().hasHeightForWidth())
        self.pushButton_autorun_charge.setSizePolicy(sizePolicy)
        self.pushButton_autorun_charge.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_charge.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_charge.setObjectName("pushButton_autorun_charge")
        self.gridLayout_4.addWidget(self.pushButton_autorun_charge, 1, 0, 1, 1)
        self.pushButton_autorun_add_water = QtWidgets.QPushButton(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_autorun_add_water.sizePolicy().hasHeightForWidth())
        self.pushButton_autorun_add_water.setSizePolicy(sizePolicy)
        self.pushButton_autorun_add_water.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_add_water.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_add_water.setObjectName("pushButton_autorun_add_water")
        self.gridLayout_4.addWidget(self.pushButton_autorun_add_water, 1, 1, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_4)
        self.verticalLayout_9.addWidget(self.groupBox_13)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_heartbeat = QtWidgets.QLabel(self.groupBox_2)
        self.label_heartbeat.setObjectName("label_heartbeat")
        self.verticalLayout_8.addWidget(self.label_heartbeat)
        self.label_robo_speed = QtWidgets.QLabel(self.groupBox_2)
        self.label_robo_speed.setObjectName("label_robo_speed")
        self.verticalLayout_8.addWidget(self.label_robo_speed)
        self.label_steer_angle = QtWidgets.QLabel(self.groupBox_2)
        self.label_steer_angle.setObjectName("label_steer_angle")
        self.verticalLayout_8.addWidget(self.label_steer_angle)
        self.label_bat_soc = QtWidgets.QLabel(self.groupBox_2)
        self.label_bat_soc.setObjectName("label_bat_soc")
        self.verticalLayout_8.addWidget(self.label_bat_soc)
        self.label_water_level = QtWidgets.QLabel(self.groupBox_2)
        self.label_water_level.setObjectName("label_water_level")
        self.verticalLayout_8.addWidget(self.label_water_level)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_drive_forward = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_drive_forward.sizePolicy().hasHeightForWidth())
        self.pushButton_drive_forward.setSizePolicy(sizePolicy)
        self.pushButton_drive_forward.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_drive_forward.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_drive_forward.setObjectName("pushButton_drive_forward")
        self.gridLayout_2.addWidget(self.pushButton_drive_forward, 0, 2, 1, 1)
        self.pushButton_drive_backward = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_drive_backward.sizePolicy().hasHeightForWidth())
        self.pushButton_drive_backward.setSizePolicy(sizePolicy)
        self.pushButton_drive_backward.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_drive_backward.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_drive_backward.setObjectName("pushButton_drive_backward")
        self.gridLayout_2.addWidget(self.pushButton_drive_backward, 2, 2, 1, 1)
        self.pushButton_drive_pause = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_drive_pause.sizePolicy().hasHeightForWidth())
        self.pushButton_drive_pause.setSizePolicy(sizePolicy)
        self.pushButton_drive_pause.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_drive_pause.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_drive_pause.setObjectName("pushButton_drive_pause")
        self.gridLayout_2.addWidget(self.pushButton_drive_pause, 1, 2, 1, 1)
        self.pushButton_turn_left = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_turn_left.sizePolicy().hasHeightForWidth())
        self.pushButton_turn_left.setSizePolicy(sizePolicy)
        self.pushButton_turn_left.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_turn_left.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_turn_left.setObjectName("pushButton_turn_left")
        self.gridLayout_2.addWidget(self.pushButton_turn_left, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 0, 1, 1)
        self.pushButton_turn_right = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_turn_right.sizePolicy().hasHeightForWidth())
        self.pushButton_turn_right.setSizePolicy(sizePolicy)
        self.pushButton_turn_right.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_turn_right.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_turn_right.setObjectName("pushButton_turn_right")
        self.gridLayout_2.addWidget(self.pushButton_turn_right, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_22.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_3.addWidget(self.pushButton_22, 0, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_7.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 0, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_15.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_3.addWidget(self.pushButton_15, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_6.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_11.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_3.addWidget(self.pushButton_11, 1, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_14.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_3.addWidget(self.pushButton_14, 1, 2, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_12)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox_2)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(250, 350))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_5.addWidget(self.textBrowser)
        self.horizontalLayout.addWidget(self.groupBox_3)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(250, 350))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_6.addWidget(self.textEdit)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_monitor_2 = QtWidgets.QWidget(self.tab_4)
        self.widget_monitor_2.setObjectName("widget_monitor_2")
        self.horizontalLayout_15.addWidget(self.widget_monitor_2)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(200, 180))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 180))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_11.addWidget(self.lineEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_11.addWidget(self.radioButton)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(20, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_5.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 2, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox_5)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_5.addWidget(self.timeEdit, 0, 3, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_6.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_6)
        self.horizontalLayout_12.addLayout(self.verticalLayout_10)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_11.addWidget(self.radioButton_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_13.addWidget(self.dateTimeEdit)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setStyleSheet("")
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.verticalLayout_7.addWidget(self.tableWidget_2)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_7)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 20, 1000, 300))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy)
        self.tableWidget_3.setMinimumSize(QtCore.QSize(1000, 300))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 361, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_14.addWidget(self.label_4)
        self.lineEdit_ip_addr = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_ip_addr.setObjectName("lineEdit_ip_addr")
        self.horizontalLayout_14.addWidget(self.lineEdit_ip_addr)
        self.pushButton_tcp_connect = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_tcp_connect.setObjectName("pushButton_tcp_connect")
        self.horizontalLayout_14.addWidget(self.pushButton_tcp_connect)
        self.pushButton_tcp_disconnect = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_tcp_disconnect.setObjectName("pushButton_tcp_disconnect")
        self.horizontalLayout_14.addWidget(self.pushButton_tcp_disconnect)
        self.verticalLayout_6.addWidget(self.groupBox_8)
        spacerItem12 = QtWidgets.QSpacerItem(20, 553, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem12)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actiona = QtWidgets.QAction(mainWindow)
        self.actiona.setObjectName("actiona")
        self.actionsave = QtWidgets.QAction(mainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionnet = QtWidgets.QAction(mainWindow)
        self.actionnet.setObjectName("actionnet")
        self.actionworklog = QtWidgets.QAction(mainWindow)
        self.actionworklog.setObjectName("actionworklog")
        self.actionrunlog = QtWidgets.QAction(mainWindow)
        self.actionrunlog.setObjectName("actionrunlog")
        self.actionabout = QtWidgets.QAction(mainWindow)
        self.actionabout.setObjectName("actionabout")
        self.menu.addAction(self.actionnet)
        self.menu.addAction(self.actiona)
        self.menu.addAction(self.actionsave)
        self.menu_2.addAction(self.actionworklog)
        self.menu_2.addAction(self.actionrunlog)
        self.menu_3.addAction(self.actionabout)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("mainWindow", "隧道"))
        self.groupBox_10.setTitle(_translate("mainWindow", "监控"))
        self.groupBox_2.setTitle(_translate("mainWindow", "机器人控制"))
        self.groupBox_13.setTitle(_translate("mainWindow", "自动运行"))
        self.pushButton_autorun_start.setText(_translate("mainWindow", "自动运行"))
        self.pushButton_autorun_stop.setText(_translate("mainWindow", "结束"))
        self.pushButton_autorun_charge.setText(_translate("mainWindow", "充电"))
        self.pushButton_autorun_add_water.setText(_translate("mainWindow", "加水"))
        self.label_heartbeat.setText(_translate("mainWindow", "通讯：正常"))
        self.label_robo_speed.setText(_translate("mainWindow", "速度：0.5m/s"))
        self.label_steer_angle.setText(_translate("mainWindow", "转向：0度"))
        self.label_bat_soc.setText(_translate("mainWindow", "电量：80%"))
        self.label_water_level.setText(_translate("mainWindow", "水位：60%"))
        self.groupBox_11.setTitle(_translate("mainWindow", "车体手动控制 "))
        self.pushButton_drive_forward.setText(_translate("mainWindow", "前进"))
        self.pushButton_drive_backward.setText(_translate("mainWindow", "后退"))
        self.pushButton_drive_pause.setText(_translate("mainWindow", "暂停"))
        self.pushButton_turn_left.setText(_translate("mainWindow", "左转"))
        self.pushButton_turn_right.setText(_translate("mainWindow", "右转"))
        self.groupBox_12.setTitle(_translate("mainWindow", "机械臂手动控制"))
        self.pushButton_22.setText(_translate("mainWindow", "诱导标3"))
        self.pushButton_7.setText(_translate("mainWindow", "诱导标2"))
        self.pushButton_15.setText(_translate("mainWindow", "诱导标1"))
        self.pushButton_6.setText(_translate("mainWindow", "反光带"))
        self.pushButton_11.setText(_translate("mainWindow", "清扫"))
        self.pushButton_14.setText(_translate("mainWindow", "归位"))
        self.groupBox_3.setTitle(_translate("mainWindow", "工作信息"))
        self.textBrowser.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">开始工作时间：9：00</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已工作时长：30分钟</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已行驶里程：600米</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已清扫反光带：400米</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已清扫诱导标：15个</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已加水：1次</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已充电：1次</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">剩余里程：200米</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">剩余时间：20分钟</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">预计完成时间：9：50</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">正在清扫诱导标……</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_4.setTitle(_translate("mainWindow", "运行信息"))
        self.textEdit.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">检测到前方障碍</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">测距传感器故障</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "控制"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("mainWindow", "监控"))
        self.groupBox_5.setTitle(_translate("mainWindow", "添加调度"))
        self.label_3.setText(_translate("mainWindow", "任务名称"))
        self.pushButton_5.setText(_translate("mainWindow", "添加"))
        self.radioButton.setText(_translate("mainWindow", "周期执行"))
        self.label_5.setText(_translate("mainWindow", "每"))
        self.label_9.setText(_translate("mainWindow", "天"))
        self.label_10.setText(_translate("mainWindow", "首次执行日期"))
        self.radioButton_2.setText(_translate("mainWindow", "选定日期执行"))
        self.groupBox_6.setTitle(_translate("mainWindow", "调度任务列表"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "2"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "任务名称"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "周期"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "执行时间"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "添加时间"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "操作"))
        self.groupBox_7.setTitle(_translate("mainWindow", "运行记录"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "1"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "2"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("mainWindow", "3"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "执行时间"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "任务名称"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "工作时长"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "工作里程"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "清理反光标"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "清理诱导标"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "调度"))
        self.groupBox_8.setTitle(_translate("mainWindow", "机器人配置"))
        self.label_4.setText(_translate("mainWindow", "机器人网络地址"))
        self.lineEdit_ip_addr.setText(_translate("mainWindow", "192.168.1.5"))
        self.pushButton_tcp_connect.setText(_translate("mainWindow", "连接"))
        self.pushButton_tcp_disconnect.setText(_translate("mainWindow", "断开"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "配置"))
        self.menu.setTitle(_translate("mainWindow", "设置"))
        self.menu_2.setTitle(_translate("mainWindow", "文件"))
        self.menu_3.setTitle(_translate("mainWindow", "帮助"))
        self.actiona.setText(_translate("mainWindow", "加载配置"))
        self.actionsave.setText(_translate("mainWindow", "保存配置"))
        self.actionnet.setText(_translate("mainWindow", "网络"))
        self.actionworklog.setText(_translate("mainWindow", "导出清扫记录"))
        self.actionrunlog.setText(_translate("mainWindow", "导出运行记录"))
        self.actionabout.setText(_translate("mainWindow", "关于"))

