# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1024, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(1024, 700))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(950, 600))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 200))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.groupBox)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.horizontalLayout_2.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setMinimumSize(QtCore.QSize(400, 200))
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_monitor = QtWidgets.QWidget(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_monitor.sizePolicy().hasHeightForWidth())
        self.widget_monitor.setSizePolicy(sizePolicy)
        self.widget_monitor.setObjectName("widget_monitor")
        self.horizontalLayout_3.addWidget(self.widget_monitor)
        self.horizontalLayout_2.addWidget(self.groupBox_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget_robo_ctrl = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_robo_ctrl.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_robo_ctrl.sizePolicy().hasHeightForWidth())
        self.tabWidget_robo_ctrl.setSizePolicy(sizePolicy)
        self.tabWidget_robo_ctrl.setMinimumSize(QtCore.QSize(300, 220))
        self.tabWidget_robo_ctrl.setMaximumSize(QtCore.QSize(300, 220))
        self.tabWidget_robo_ctrl.setObjectName("tabWidget_robo_ctrl")
        self.tab_auto_clean = QtWidgets.QWidget()
        self.tab_auto_clean.setObjectName("tab_auto_clean")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_auto_clean)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_autorun_charge = QtWidgets.QPushButton(self.tab_auto_clean)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_autorun_charge.sizePolicy().hasHeightForWidth())
        self.pushButton_autorun_charge.setSizePolicy(sizePolicy)
        self.pushButton_autorun_charge.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_charge.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_charge.setObjectName("pushButton_autorun_charge")
        self.gridLayout_2.addWidget(self.pushButton_autorun_charge, 1, 0, 1, 1)
        self.pushButton_autorun_add_water = QtWidgets.QPushButton(self.tab_auto_clean)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_autorun_add_water.sizePolicy().hasHeightForWidth())
        self.pushButton_autorun_add_water.setSizePolicy(sizePolicy)
        self.pushButton_autorun_add_water.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_add_water.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_add_water.setObjectName("pushButton_autorun_add_water")
        self.gridLayout_2.addWidget(self.pushButton_autorun_add_water, 1, 1, 1, 1)
        self.pushButton_autorun_start = QtWidgets.QPushButton(self.tab_auto_clean)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_autorun_start.sizePolicy().hasHeightForWidth())
        self.pushButton_autorun_start.setSizePolicy(sizePolicy)
        self.pushButton_autorun_start.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_start.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_start.setObjectName("pushButton_autorun_start")
        self.gridLayout_2.addWidget(self.pushButton_autorun_start, 0, 0, 1, 1)
        self.pushButton_autorun_stop = QtWidgets.QPushButton(self.tab_auto_clean)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_autorun_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_autorun_stop.setSizePolicy(sizePolicy)
        self.pushButton_autorun_stop.setMinimumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_stop.setMaximumSize(QtCore.QSize(70, 40))
        self.pushButton_autorun_stop.setObjectName("pushButton_autorun_stop")
        self.gridLayout_2.addWidget(self.pushButton_autorun_stop, 0, 1, 1, 1)
        self.tabWidget_robo_ctrl.addTab(self.tab_auto_clean, "")
        self.tab_chassis_ctrl = QtWidgets.QWidget()
        self.tab_chassis_ctrl.setObjectName("tab_chassis_ctrl")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_chassis_ctrl)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label = QtWidgets.QLabel(self.tab_chassis_ctrl)
        self.label.setObjectName("label")
        self.horizontalLayout_18.addWidget(self.label)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalSlider_robo_speed = QtWidgets.QSlider(self.tab_chassis_ctrl)
        self.horizontalSlider_robo_speed.setMinimumSize(QtCore.QSize(0, 20))
        self.horizontalSlider_robo_speed.setMinimum(-300)
        self.horizontalSlider_robo_speed.setMaximum(300)
        self.horizontalSlider_robo_speed.setSingleStep(10)
        self.horizontalSlider_robo_speed.setPageStep(50)
        self.horizontalSlider_robo_speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_robo_speed.setInvertedAppearance(False)
        self.horizontalSlider_robo_speed.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_robo_speed.setObjectName("horizontalSlider_robo_speed")
        self.verticalLayout_15.addWidget(self.horizontalSlider_robo_speed)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.spinBox_robo_speed = QtWidgets.QSpinBox(self.tab_chassis_ctrl)
        self.spinBox_robo_speed.setMinimum(-300)
        self.spinBox_robo_speed.setMaximum(300)
        self.spinBox_robo_speed.setSingleStep(10)
        self.spinBox_robo_speed.setProperty("value", 0)
        self.spinBox_robo_speed.setObjectName("spinBox_robo_speed")
        self.horizontalLayout_16.addWidget(self.spinBox_robo_speed)
        self.label_6 = QtWidgets.QLabel(self.tab_chassis_ctrl)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_16.addWidget(self.label_6)
        self.pushButton_robo_speed_zero = QtWidgets.QPushButton(self.tab_chassis_ctrl)
        self.pushButton_robo_speed_zero.setObjectName("pushButton_robo_speed_zero")
        self.horizontalLayout_16.addWidget(self.pushButton_robo_speed_zero)
        self.verticalLayout_15.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18.addLayout(self.verticalLayout_15)
        self.dial_robo_speed = QtWidgets.QDial(self.tab_chassis_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_robo_speed.sizePolicy().hasHeightForWidth())
        self.dial_robo_speed.setSizePolicy(sizePolicy)
        self.dial_robo_speed.setMinimumSize(QtCore.QSize(80, 80))
        self.dial_robo_speed.setMaximumSize(QtCore.QSize(80, 80))
        self.dial_robo_speed.setMouseTracking(False)
        self.dial_robo_speed.setTabletTracking(False)
        self.dial_robo_speed.setAutoFillBackground(False)
        self.dial_robo_speed.setMinimum(-300)
        self.dial_robo_speed.setMaximum(300)
        self.dial_robo_speed.setSingleStep(10)
        self.dial_robo_speed.setPageStep(50)
        self.dial_robo_speed.setSliderPosition(0)
        self.dial_robo_speed.setInvertedAppearance(False)
        self.dial_robo_speed.setInvertedControls(False)
        self.dial_robo_speed.setWrapping(False)
        self.dial_robo_speed.setNotchTarget(50.0)
        self.dial_robo_speed.setNotchesVisible(False)
        self.dial_robo_speed.setObjectName("dial_robo_speed")
        self.horizontalLayout_18.addWidget(self.dial_robo_speed)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_2 = QtWidgets.QLabel(self.tab_chassis_ctrl)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_19.addWidget(self.label_2)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalSlider_steer_angle = QtWidgets.QSlider(self.tab_chassis_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_steer_angle.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_steer_angle.setSizePolicy(sizePolicy)
        self.horizontalSlider_steer_angle.setMinimumSize(QtCore.QSize(0, 20))
        self.horizontalSlider_steer_angle.setMinimum(-30)
        self.horizontalSlider_steer_angle.setMaximum(30)
        self.horizontalSlider_steer_angle.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_steer_angle.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_steer_angle.setObjectName("horizontalSlider_steer_angle")
        self.verticalLayout_16.addWidget(self.horizontalSlider_steer_angle)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.spinBox_steer_angle = QtWidgets.QSpinBox(self.tab_chassis_ctrl)
        self.spinBox_steer_angle.setMinimum(-30)
        self.spinBox_steer_angle.setMaximum(30)
        self.spinBox_steer_angle.setObjectName("spinBox_steer_angle")
        self.horizontalLayout_17.addWidget(self.spinBox_steer_angle)
        self.label_7 = QtWidgets.QLabel(self.tab_chassis_ctrl)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_17.addWidget(self.label_7)
        self.pushButton_steer_angle_zero = QtWidgets.QPushButton(self.tab_chassis_ctrl)
        self.pushButton_steer_angle_zero.setObjectName("pushButton_steer_angle_zero")
        self.horizontalLayout_17.addWidget(self.pushButton_steer_angle_zero)
        self.verticalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_19.addLayout(self.verticalLayout_16)
        self.dial_steer_angle = QtWidgets.QDial(self.tab_chassis_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_steer_angle.sizePolicy().hasHeightForWidth())
        self.dial_steer_angle.setSizePolicy(sizePolicy)
        self.dial_steer_angle.setMinimumSize(QtCore.QSize(80, 80))
        self.dial_steer_angle.setMaximumSize(QtCore.QSize(80, 80))
        self.dial_steer_angle.setMouseTracking(False)
        self.dial_steer_angle.setTabletTracking(False)
        self.dial_steer_angle.setAutoFillBackground(False)
        self.dial_steer_angle.setMinimum(-30)
        self.dial_steer_angle.setMaximum(30)
        self.dial_steer_angle.setSliderPosition(0)
        self.dial_steer_angle.setInvertedAppearance(False)
        self.dial_steer_angle.setInvertedControls(False)
        self.dial_steer_angle.setWrapping(False)
        self.dial_steer_angle.setNotchTarget(50.0)
        self.dial_steer_angle.setNotchesVisible(False)
        self.dial_steer_angle.setObjectName("dial_steer_angle")
        self.horizontalLayout_19.addWidget(self.dial_steer_angle)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.pushButton_chassis_power_restart = QtWidgets.QPushButton(self.tab_chassis_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_chassis_power_restart.sizePolicy().hasHeightForWidth())
        self.pushButton_chassis_power_restart.setSizePolicy(sizePolicy)
        self.pushButton_chassis_power_restart.setMinimumSize(QtCore.QSize(80, 23))
        self.pushButton_chassis_power_restart.setMaximumSize(QtCore.QSize(100, 23))
        self.pushButton_chassis_power_restart.setObjectName("pushButton_chassis_power_restart")
        self.horizontalLayout_6.addWidget(self.pushButton_chassis_power_restart)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.tabWidget_robo_ctrl.addTab(self.tab_chassis_ctrl, "")
        self.tab_arm_ctrl = QtWidgets.QWidget()
        self.tab_arm_ctrl.setObjectName("tab_arm_ctrl")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_arm_ctrl)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_arm_position_ground_1 = QtWidgets.QPushButton(self.tab_arm_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_arm_position_ground_1.sizePolicy().hasHeightForWidth())
        self.pushButton_arm_position_ground_1.setSizePolicy(sizePolicy)
        self.pushButton_arm_position_ground_1.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_arm_position_ground_1.setMaximumSize(QtCore.QSize(60, 40))
        self.pushButton_arm_position_ground_1.setObjectName("pushButton_arm_position_ground_1")
        self.gridLayout_3.addWidget(self.pushButton_arm_position_ground_1, 1, 0, 1, 1)
        self.pushButton_arm_position_wall_2 = QtWidgets.QPushButton(self.tab_arm_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_arm_position_wall_2.sizePolicy().hasHeightForWidth())
        self.pushButton_arm_position_wall_2.setSizePolicy(sizePolicy)
        self.pushButton_arm_position_wall_2.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_arm_position_wall_2.setMaximumSize(QtCore.QSize(60, 40))
        self.pushButton_arm_position_wall_2.setObjectName("pushButton_arm_position_wall_2")
        self.gridLayout_3.addWidget(self.pushButton_arm_position_wall_2, 0, 1, 1, 1)
        self.pushButton_arm_position_wall_3 = QtWidgets.QPushButton(self.tab_arm_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_arm_position_wall_3.sizePolicy().hasHeightForWidth())
        self.pushButton_arm_position_wall_3.setSizePolicy(sizePolicy)
        self.pushButton_arm_position_wall_3.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_arm_position_wall_3.setMaximumSize(QtCore.QSize(60, 40))
        self.pushButton_arm_position_wall_3.setObjectName("pushButton_arm_position_wall_3")
        self.gridLayout_3.addWidget(self.pushButton_arm_position_wall_3, 0, 2, 1, 1)
        self.pushButton_arm_position_wall_1 = QtWidgets.QPushButton(self.tab_arm_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_arm_position_wall_1.sizePolicy().hasHeightForWidth())
        self.pushButton_arm_position_wall_1.setSizePolicy(sizePolicy)
        self.pushButton_arm_position_wall_1.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_arm_position_wall_1.setMaximumSize(QtCore.QSize(60, 40))
        self.pushButton_arm_position_wall_1.setObjectName("pushButton_arm_position_wall_1")
        self.gridLayout_3.addWidget(self.pushButton_arm_position_wall_1, 0, 0, 1, 1)
        self.pushButton_arm_position_wall_4 = QtWidgets.QPushButton(self.tab_arm_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_arm_position_wall_4.sizePolicy().hasHeightForWidth())
        self.pushButton_arm_position_wall_4.setSizePolicy(sizePolicy)
        self.pushButton_arm_position_wall_4.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_arm_position_wall_4.setMaximumSize(QtCore.QSize(60, 40))
        self.pushButton_arm_position_wall_4.setObjectName("pushButton_arm_position_wall_4")
        self.gridLayout_3.addWidget(self.pushButton_arm_position_wall_4, 0, 3, 1, 1)
        self.pushButton_arm_position_origin = QtWidgets.QPushButton(self.tab_arm_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_arm_position_origin.sizePolicy().hasHeightForWidth())
        self.pushButton_arm_position_origin.setSizePolicy(sizePolicy)
        self.pushButton_arm_position_origin.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_arm_position_origin.setMaximumSize(QtCore.QSize(60, 40))
        self.pushButton_arm_position_origin.setObjectName("pushButton_arm_position_origin")
        self.gridLayout_3.addWidget(self.pushButton_arm_position_origin, 1, 1, 1, 1)
        self.pushButton_work_clean = QtWidgets.QPushButton(self.tab_arm_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_work_clean.sizePolicy().hasHeightForWidth())
        self.pushButton_work_clean.setSizePolicy(sizePolicy)
        self.pushButton_work_clean.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_work_clean.setMaximumSize(QtCore.QSize(60, 40))
        self.pushButton_work_clean.setCheckable(True)
        self.pushButton_work_clean.setObjectName("pushButton_work_clean")
        self.gridLayout_3.addWidget(self.pushButton_work_clean, 1, 2, 1, 1)
        self.pushButton_arm_power_restart = QtWidgets.QPushButton(self.tab_arm_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_arm_power_restart.sizePolicy().hasHeightForWidth())
        self.pushButton_arm_power_restart.setSizePolicy(sizePolicy)
        self.pushButton_arm_power_restart.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_arm_power_restart.setMaximumSize(QtCore.QSize(60, 40))
        self.pushButton_arm_power_restart.setObjectName("pushButton_arm_power_restart")
        self.gridLayout_3.addWidget(self.pushButton_arm_power_restart, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.tabWidget_robo_ctrl.addTab(self.tab_arm_ctrl, "")
        self.horizontalLayout.addWidget(self.tabWidget_robo_ctrl)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_12.setMinimumSize(QtCore.QSize(120, 200))
        self.groupBox_12.setMaximumSize(QtCore.QSize(120, 220))
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_heartbeat = QtWidgets.QLabel(self.groupBox_12)
        self.label_heartbeat.setObjectName("label_heartbeat")
        self.verticalLayout_8.addWidget(self.label_heartbeat)
        self.label_robo_speed = QtWidgets.QLabel(self.groupBox_12)
        self.label_robo_speed.setObjectName("label_robo_speed")
        self.verticalLayout_8.addWidget(self.label_robo_speed)
        self.label_steer_angle = QtWidgets.QLabel(self.groupBox_12)
        self.label_steer_angle.setObjectName("label_steer_angle")
        self.verticalLayout_8.addWidget(self.label_steer_angle)
        self.label_bat_soc = QtWidgets.QLabel(self.groupBox_12)
        self.label_bat_soc.setObjectName("label_bat_soc")
        self.verticalLayout_8.addWidget(self.label_bat_soc)
        self.label_water_level = QtWidgets.QLabel(self.groupBox_12)
        self.label_water_level.setObjectName("label_water_level")
        self.verticalLayout_8.addWidget(self.label_water_level)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addWidget(self.groupBox_12)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 220))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_5.addWidget(self.textBrowser)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(250, 200))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 220))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_monitor_2 = QtWidgets.QWidget(self.tab_4)
        self.widget_monitor_2.setObjectName("widget_monitor_2")
        self.horizontalLayout_15.addWidget(self.widget_monitor_2)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_11.addWidget(self.lineEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_11.addWidget(self.radioButton)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(20, 0))
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_5.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 2, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox_5)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_5.addWidget(self.timeEdit, 0, 3, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_6.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_6)
        self.horizontalLayout_12.addLayout(self.verticalLayout_10)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_11.addWidget(self.radioButton_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_13.addWidget(self.dateTimeEdit)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(800, 150))
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_2.sizePolicy().hasHeightForWidth())
        self.tableWidget_2.setSizePolicy(sizePolicy)
        self.tableWidget_2.setStyleSheet("")
        self.tableWidget_2.setShowGrid(True)
        self.tableWidget_2.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.verticalLayout_7.addWidget(self.tableWidget_2)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy)
        self.tableWidget_3.setMinimumSize(QtCore.QSize(1000, 300))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        self.verticalLayout_14.addWidget(self.tableWidget_3)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.verticalLayout_13.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_14.addWidget(self.label_4)
        self.lineEdit_ip_addr = QtWidgets.QLineEdit(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ip_addr.sizePolicy().hasHeightForWidth())
        self.lineEdit_ip_addr.setSizePolicy(sizePolicy)
        self.lineEdit_ip_addr.setMinimumSize(QtCore.QSize(150, 20))
        self.lineEdit_ip_addr.setMaximumSize(QtCore.QSize(150, 20))
        self.lineEdit_ip_addr.setObjectName("lineEdit_ip_addr")
        self.horizontalLayout_14.addWidget(self.lineEdit_ip_addr)
        self.pushButton_tcp_connect = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_tcp_connect.setObjectName("pushButton_tcp_connect")
        self.horizontalLayout_14.addWidget(self.pushButton_tcp_connect)
        self.pushButton_tcp_disconnect = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_tcp_disconnect.setObjectName("pushButton_tcp_disconnect")
        self.horizontalLayout_14.addWidget(self.pushButton_tcp_disconnect)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.label_connect_info = QtWidgets.QLabel(self.groupBox_8)
        self.label_connect_info.setObjectName("label_connect_info")
        self.verticalLayout_12.addWidget(self.label_connect_info)
        self.label_robo_info = QtWidgets.QLabel(self.groupBox_8)
        self.label_robo_info.setText("")
        self.label_robo_info.setObjectName("label_robo_info")
        self.verticalLayout_12.addWidget(self.label_robo_info)
        self.verticalLayout_6.addWidget(self.groupBox_8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actiona = QtWidgets.QAction(mainWindow)
        self.actiona.setObjectName("actiona")
        self.actionsave = QtWidgets.QAction(mainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionnet = QtWidgets.QAction(mainWindow)
        self.actionnet.setObjectName("actionnet")
        self.actionworklog = QtWidgets.QAction(mainWindow)
        self.actionworklog.setObjectName("actionworklog")
        self.actionrunlog = QtWidgets.QAction(mainWindow)
        self.actionrunlog.setObjectName("actionrunlog")
        self.actionabout = QtWidgets.QAction(mainWindow)
        self.actionabout.setObjectName("actionabout")
        self.menu.addAction(self.actionnet)
        self.menu.addAction(self.actiona)
        self.menu.addAction(self.actionsave)
        self.menu_2.addAction(self.actionworklog)
        self.menu_2.addAction(self.actionrunlog)
        self.menu_3.addAction(self.actionabout)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_robo_ctrl.setCurrentIndex(0)
        self.horizontalSlider_robo_speed.valueChanged['int'].connect(self.spinBox_robo_speed.setValue)
        self.horizontalSlider_robo_speed.valueChanged['int'].connect(self.dial_robo_speed.setValue)
        self.dial_robo_speed.valueChanged['int'].connect(self.horizontalSlider_robo_speed.setValue)
        self.dial_robo_speed.valueChanged['int'].connect(self.spinBox_robo_speed.setValue)
        self.spinBox_robo_speed.valueChanged['int'].connect(self.horizontalSlider_robo_speed.setValue)
        self.spinBox_robo_speed.valueChanged['int'].connect(self.dial_robo_speed.setValue)
        self.horizontalSlider_steer_angle.valueChanged['int'].connect(self.spinBox_steer_angle.setValue)
        self.horizontalSlider_steer_angle.valueChanged['int'].connect(self.dial_steer_angle.setValue)
        self.spinBox_steer_angle.valueChanged['int'].connect(self.horizontalSlider_steer_angle.setValue)
        self.spinBox_steer_angle.valueChanged['int'].connect(self.dial_steer_angle.setValue)
        self.dial_steer_angle.valueChanged['int'].connect(self.horizontalSlider_steer_angle.setValue)
        self.dial_steer_angle.valueChanged['int'].connect(self.spinBox_steer_angle.setValue)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "隧道清扫机器人控制"))
        self.groupBox.setTitle(_translate("mainWindow", "隧道"))
        self.groupBox_10.setTitle(_translate("mainWindow", "监控"))
        self.pushButton_autorun_charge.setText(_translate("mainWindow", "充电"))
        self.pushButton_autorun_add_water.setText(_translate("mainWindow", "加水"))
        self.pushButton_autorun_start.setText(_translate("mainWindow", "开始清扫"))
        self.pushButton_autorun_stop.setText(_translate("mainWindow", "结束清扫"))
        self.tabWidget_robo_ctrl.setTabText(self.tabWidget_robo_ctrl.indexOf(self.tab_auto_clean), _translate("mainWindow", "清扫任务"))
        self.label.setText(_translate("mainWindow", "车速"))
        self.label_6.setText(_translate("mainWindow", "mm/s"))
        self.pushButton_robo_speed_zero.setText(_translate("mainWindow", "暂停"))
        self.label_2.setText(_translate("mainWindow", "转向"))
        self.label_7.setText(_translate("mainWindow", "度"))
        self.pushButton_steer_angle_zero.setText(_translate("mainWindow", "转向回正"))
        self.pushButton_chassis_power_restart.setText(_translate("mainWindow", "重新上电"))
        self.tabWidget_robo_ctrl.setTabText(self.tabWidget_robo_ctrl.indexOf(self.tab_chassis_ctrl), _translate("mainWindow", "底盘控制"))
        self.pushButton_arm_position_ground_1.setText(_translate("mainWindow", "地面1"))
        self.pushButton_arm_position_wall_2.setText(_translate("mainWindow", "侧壁2"))
        self.pushButton_arm_position_wall_3.setText(_translate("mainWindow", "侧壁3"))
        self.pushButton_arm_position_wall_1.setText(_translate("mainWindow", "侧壁1"))
        self.pushButton_arm_position_wall_4.setText(_translate("mainWindow", "侧壁4"))
        self.pushButton_arm_position_origin.setText(_translate("mainWindow", "归位"))
        self.pushButton_work_clean.setText(_translate("mainWindow", "开滚刷"))
        self.pushButton_arm_power_restart.setText(_translate("mainWindow", "重新上电"))
        self.tabWidget_robo_ctrl.setTabText(self.tabWidget_robo_ctrl.indexOf(self.tab_arm_ctrl), _translate("mainWindow", "机械臂控制"))
        self.groupBox_12.setTitle(_translate("mainWindow", "机器人状态"))
        self.label_heartbeat.setText(_translate("mainWindow", "通讯：--"))
        self.label_robo_speed.setText(_translate("mainWindow", "速度：--mm/s"))
        self.label_steer_angle.setText(_translate("mainWindow", "转向：--度"))
        self.label_bat_soc.setText(_translate("mainWindow", "电量：--%"))
        self.label_water_level.setText(_translate("mainWindow", "水位：--%"))
        self.groupBox_3.setTitle(_translate("mainWindow", "工作信息"))
        self.textBrowser.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">开始工作时间：9：00</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已工作时长：30分钟</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已行驶里程：600米</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已清扫反光带：400米</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已清扫诱导标：15个</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已加水：1次</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">已充电：1次</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">剩余里程：200米</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">剩余时间：20分钟</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">预计完成时间：9：50</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">正在清扫诱导标……</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_4.setTitle(_translate("mainWindow", "运行信息"))
        self.textEdit.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">检测到前方障碍</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">测距传感器故障</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "控制"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("mainWindow", "监控"))
        self.groupBox_5.setTitle(_translate("mainWindow", "添加调度"))
        self.label_3.setText(_translate("mainWindow", "任务名称"))
        self.pushButton_5.setText(_translate("mainWindow", "添加"))
        self.radioButton.setText(_translate("mainWindow", "周期执行"))
        self.label_5.setText(_translate("mainWindow", "每"))
        self.label_9.setText(_translate("mainWindow", "天"))
        self.label_10.setText(_translate("mainWindow", "首次执行日期"))
        self.radioButton_2.setText(_translate("mainWindow", "选定日期执行"))
        self.groupBox_6.setTitle(_translate("mainWindow", "调度任务列表"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "2"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "任务名称"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "周期"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "执行时间"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "添加时间"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "操作"))
        self.groupBox_7.setTitle(_translate("mainWindow", "运行记录"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("mainWindow", "1"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("mainWindow", "2"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("mainWindow", "3"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "执行时间"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "任务名称"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "工作时长"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "工作里程"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "清理反光标"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "清理诱导标"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "调度"))
        self.groupBox_8.setTitle(_translate("mainWindow", "机器人配置"))
        self.label_4.setText(_translate("mainWindow", "机器人网络地址"))
        self.lineEdit_ip_addr.setText(_translate("mainWindow", "192.168.1.5"))
        self.pushButton_tcp_connect.setText(_translate("mainWindow", "连接"))
        self.pushButton_tcp_disconnect.setText(_translate("mainWindow", "断开"))
        self.label_connect_info.setText(_translate("mainWindow", "网络未连接"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "配置"))
        self.menu.setTitle(_translate("mainWindow", "设置"))
        self.menu_2.setTitle(_translate("mainWindow", "文件"))
        self.menu_3.setTitle(_translate("mainWindow", "帮助"))
        self.actiona.setText(_translate("mainWindow", "加载配置"))
        self.actionsave.setText(_translate("mainWindow", "保存配置"))
        self.actionnet.setText(_translate("mainWindow", "网络"))
        self.actionworklog.setText(_translate("mainWindow", "导出清扫记录"))
        self.actionrunlog.setText(_translate("mainWindow", "导出运行记录"))
        self.actionabout.setText(_translate("mainWindow", "关于"))

